apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: This is Team A
spec:
  type: team
  profile:
    displayName: Team A
    email: team-a@example.com
  children: []
